import { ALL_AI_TOOLS, ALL_COMMANDS, ALL_DOCS, ALL_OPTIONAL_PACKAGES } from "./constants.js";
import type { Preset, PresetName } from "./types.js";

export const PRESETS: Record<PresetName, Preset> = {
  "fullstack-next": {
    name: "fullstack-next",
    label: "Fullstack Next.js + Supabase",
    frontend: "nextjs",
    backend: "supabase",
    aiTools: ["claude", "cursor"],
    commands: ALL_COMMANDS,
    docs: ALL_DOCS,
    includeConstitution: true,
    includeSkillsGuide: false,
    scaffoldProject: true,
    includeShadcn: true,
    dxTooling: true,
    packages: [],
  },
  "fullstack-vite": {
    name: "fullstack-vite",
    label: "Fullstack Vite + Supabase",
    frontend: "vite",
    backend: "supabase",
    aiTools: ["claude", "cursor"],
    commands: ALL_COMMANDS,
    docs: ALL_DOCS,
    includeConstitution: true,
    includeSkillsGuide: false,
    scaffoldProject: true,
    includeShadcn: true,
    dxTooling: true,
    packages: [],
  },
  landing: {
    name: "landing",
    label: "Landing page Astro",
    frontend: "astro",
    backend: "none",
    aiTools: ["claude"],
    commands: ["kiss", "yagni", "validate"],
    docs: [
      "principes",
      "qualite-code",
      "typescript-conventions",
      "css-design-tokens",
      "performance",
      "accessibilite",
      "git-workflow",
      "configs-partagees",
    ],
    includeConstitution: false,
    includeSkillsGuide: false,
    scaffoldProject: true,
    includeShadcn: false,
    dxTooling: true,
    packages: [],
  },
  minimal: {
    name: "minimal",
    label: "Minimal — principes seuls",
    frontend: "nextjs",
    backend: "none",
    aiTools: ["claude"],
    commands: ["validate"],
    docs: ["principes", "qualite-code", "typescript-conventions", "configs-partagees"],
    includeConstitution: false,
    includeSkillsGuide: false,
    scaffoldProject: false,
    includeShadcn: false,
    dxTooling: true,
    packages: [],
  },
  all: {
    name: "all",
    label: "Tout inclure",
    frontend: "nextjs",
    backend: "supabase",
    aiTools: ALL_AI_TOOLS,
    commands: ALL_COMMANDS,
    docs: ALL_DOCS,
    includeConstitution: true,
    includeSkillsGuide: true,
    scaffoldProject: true,
    includeShadcn: true,
    dxTooling: true,
    packages: ALL_OPTIONAL_PACKAGES,
  },
};

export function getPreset(name: string): Preset | undefined {
  return PRESETS[name as PresetName];
}
